### ISSUE TITLE
UnX Crashes as soon as FFX Opens

### ISSUE THREAD

**Issue by BearWaifu** [Kaldaien/UnX#59]
Crash Report, I think: http://pastebin.com/yPPLesgC

Every single time I open FFX while trying to use the mod, I get a white screen. Then, the Metal Gear '!' noise plays, and it crashes soon after. I'm not sure why. Any way you can help?

**Comment by Kaldaien** [comment]
The crash log isn't enough information to diagnose this problem.

There is a stack overflow in a place I cannot explain, which usually means third-party software is doing something weird. Can you include the rest of the logs such as logs/preloads.log, steam_api.log, dxgi.log, etc?

**Comment by BearWaifu** [comment]
http://pastebin.com/jDcz5JuE -crash.log
http://pastebin.com/ZkEm8Zuv -dxgi.log
http://pastebin.com/ATjeSYzM -preloads.log
http://pastebin.com/Ndqkw8c2 -steam_api.log
http://pastebin.com/n09tJrpw -Unx.log

I believe this is what you're looking for? Also, I'm not familiar with Radeon Pro, so it might be the problem?

**Comment by Kaldaien** [comment]
Okay, it's behaving a lot like a pirated copy of Steam software for some reason. I see that the game's installed to a valid Steam location, so I imagine you actually do own the game...

Can you set **Silent=true** under [Steam.Log] in `dxgi.ini`?

**Comment by BearWaifu** [comment]
Yep, done. Anything else?

**Comment by Kaldaien** [comment]
I didn't think this needed to be said, but... can you also run the game after doing that and post the results? :)

**Comment by BearWaifu** [comment]
Oh, pfft, of course. Sorry. All the logs?

**Comment by BearWaifu** [comment]
http://pastebin.com/vCT52rR2 -Crash.log post silence
http://pastebin.com/WH3wWrMC -dxgi.log post silence
http://pastebin.com/Xj5UJEzQ -game_output.log post silence
http://pastebin.com/Vv1FdAEh -preloads.log post silence
steam_api.log was empty
http://pastebin.com/hxRMqMtJ -unx.log post silence

**Comment by Aitamen** [comment]
Encountering a similar problem.  Wanted to note that the command prompt doesn't show up on v8.1, but it does on 7.3, if it's relevant.  No crash logs.

**Comment by BearWaifu** [comment]
Command prompt is showing up, so what exactly does that mean for me?

**Comment by waldnercharles** [comment]
I'm running into the same issue.

**Comment by BearWaifu** [comment]
Oh, pfft, I'm dumb, thought thst was K.

**Comment by argiopetech** [comment]
Same issue with FFX/FFX-2. Logs for the latter at https://gist.github.com/argiopetech/f761f6e93d360ce701fb4cbedb5767d4.

Run in 1280x720 windowed via the steam launcher. Hardware is AMD A10 with integrated graphics. With the exception of silencing steam log, UnX config files are default as installed by SKIM64 (v. 0.8.2.1). Console appears but remains blank, The "Square Enix" logo begins to appear just prior to the (!) sound.

**Comment by Sechs** [comment]
Same situation here. Testing and Main not working (crash) but Compatibility seem to work fine.

**Comment by Kaldaien** [comment]
The testing branch should have this all sorted out ***finally***. Compiler optimizations I didn't really want were causing certain important hooked functions to disappear.

I cannot explain why it wasn't causing problems on any of my test machines, but the common crash seen in all the logs should be resolved.

**Comment by bgolemba** [comment]
I have been experiencing the same issue
Here is log:
crash.log: [https://pastebin.com/Ghd0udDt](https://pastebin.com/Ghd0udDt)
dxgi.log: [https://pastebin.com/7TiLYk7K](https://pastebin.com/7TiLYk7K)
modules.log: [https://pastebin.com/a41nmpMG](https://pastebin.com/a41nmpMG)

**Comment by iJinzoi** [comment]
... I attempted this a few years ago and it didn't work, and I'm still getting the issue. Though my '!' sound happens the moment I press to open the UI. Game crashes and all. I've tried to validate the game files and all, to no avail. Can anyone help me out here?
